// Code generated by entc, DO NOT EDIT.

package getoffwork

const (
	// Label holds the string label denoting the getoffwork type in the database.
	Label = "get_off_work"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGetOffWork holds the string denoting the getoffwork field in the database.
	FieldGetOffWork = "get_off_work"

	// EdgeWhenendwork holds the string denoting the whenendwork edge name in mutations.
	EdgeWhenendwork = "whenendwork"

	// Table holds the table name of the getoffwork in the database.
	Table = "get_off_works"
	// WhenendworkTable is the table the holds the whenendwork relation/edge.
	WhenendworkTable = "employee_working_hours"
	// WhenendworkInverseTable is the table name for the EmployeeWorkingHours entity.
	// It exists in this package in order to avoid circular dependency with the "employeeworkinghours" package.
	WhenendworkInverseTable = "employee_working_hours"
	// WhenendworkColumn is the table column denoting the whenendwork relation/edge.
	WhenendworkColumn = "get_off_work_whenendwork"
)

// Columns holds all SQL columns for getoffwork fields.
var Columns = []string{
	FieldID,
	FieldGetOffWork,
}
