// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/tanapon395/playlist-video/ent/assessment"
)

// Assessment is the model entity for the Assessment schema.
type Assessment struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Assessment holds the value of the "assessment" field.
	Assessment string `json:"assessment,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AssessmentQuery when eager-loading is set.
	Edges AssessmentEdges `json:"edges"`
}

// AssessmentEdges holds the relations/edges for other nodes in the graph.
type AssessmentEdges struct {
	// Formassessment holds the value of the formassessment edge.
	Formassessment []*Salary
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// FormassessmentOrErr returns the Formassessment value or an error if the edge
// was not loaded in eager-loading.
func (e AssessmentEdges) FormassessmentOrErr() ([]*Salary, error) {
	if e.loadedTypes[0] {
		return e.Formassessment, nil
	}
	return nil, &NotLoadedError{edge: "formassessment"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Assessment) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // assessment
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Assessment fields.
func (a *Assessment) assignValues(values ...interface{}) error {
	if m, n := len(values), len(assessment.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	a.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field assessment", values[0])
	} else if value.Valid {
		a.Assessment = value.String
	}
	return nil
}

// QueryFormassessment queries the formassessment edge of the Assessment.
func (a *Assessment) QueryFormassessment() *SalaryQuery {
	return (&AssessmentClient{config: a.config}).QueryFormassessment(a)
}

// Update returns a builder for updating this Assessment.
// Note that, you need to call Assessment.Unwrap() before calling this method, if this Assessment
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *Assessment) Update() *AssessmentUpdateOne {
	return (&AssessmentClient{config: a.config}).UpdateOne(a)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (a *Assessment) Unwrap() *Assessment {
	tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("ent: Assessment is not a transactional entity")
	}
	a.config.driver = tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *Assessment) String() string {
	var builder strings.Builder
	builder.WriteString("Assessment(")
	builder.WriteString(fmt.Sprintf("id=%v", a.ID))
	builder.WriteString(", assessment=")
	builder.WriteString(a.Assessment)
	builder.WriteByte(')')
	return builder.String()
}

// Assessments is a parsable slice of Assessment.
type Assessments []*Assessment

func (a Assessments) config(cfg config) {
	for _i := range a {
		a[_i].config = cfg
	}
}
