// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/team13/app/ent/beginwork"
	"github.com/team13/app/ent/employeeworkinghours"
	"github.com/team13/app/ent/predicate"
)

// BeginWorkUpdate is the builder for updating BeginWork entities.
type BeginWorkUpdate struct {
	config
	hooks      []Hook
	mutation   *BeginWorkMutation
	predicates []predicate.BeginWork
}

// Where adds a new predicate for the builder.
func (bwu *BeginWorkUpdate) Where(ps ...predicate.BeginWork) *BeginWorkUpdate {
	bwu.predicates = append(bwu.predicates, ps...)
	return bwu
}

// SetBeginWork sets the BeginWork field.
func (bwu *BeginWorkUpdate) SetBeginWork(t time.Time) *BeginWorkUpdate {
	bwu.mutation.SetBeginWork(t)
	return bwu
}

// AddWhenworkIDs adds the whenwork edge to EmployeeWorkingHours by ids.
func (bwu *BeginWorkUpdate) AddWhenworkIDs(ids ...int) *BeginWorkUpdate {
	bwu.mutation.AddWhenworkIDs(ids...)
	return bwu
}

// AddWhenwork adds the whenwork edges to EmployeeWorkingHours.
func (bwu *BeginWorkUpdate) AddWhenwork(e ...*EmployeeWorkingHours) *BeginWorkUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return bwu.AddWhenworkIDs(ids...)
}

// Mutation returns the BeginWorkMutation object of the builder.
func (bwu *BeginWorkUpdate) Mutation() *BeginWorkMutation {
	return bwu.mutation
}

// RemoveWhenworkIDs removes the whenwork edge to EmployeeWorkingHours by ids.
func (bwu *BeginWorkUpdate) RemoveWhenworkIDs(ids ...int) *BeginWorkUpdate {
	bwu.mutation.RemoveWhenworkIDs(ids...)
	return bwu
}

// RemoveWhenwork removes whenwork edges to EmployeeWorkingHours.
func (bwu *BeginWorkUpdate) RemoveWhenwork(e ...*EmployeeWorkingHours) *BeginWorkUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return bwu.RemoveWhenworkIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (bwu *BeginWorkUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(bwu.hooks) == 0 {
		affected, err = bwu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BeginWorkMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bwu.mutation = mutation
			affected, err = bwu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(bwu.hooks) - 1; i >= 0; i-- {
			mut = bwu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bwu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (bwu *BeginWorkUpdate) SaveX(ctx context.Context) int {
	affected, err := bwu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bwu *BeginWorkUpdate) Exec(ctx context.Context) error {
	_, err := bwu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bwu *BeginWorkUpdate) ExecX(ctx context.Context) {
	if err := bwu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (bwu *BeginWorkUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   beginwork.Table,
			Columns: beginwork.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: beginwork.FieldID,
			},
		},
	}
	if ps := bwu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bwu.mutation.BeginWork(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: beginwork.FieldBeginWork,
		})
	}
	if nodes := bwu.mutation.RemovedWhenworkIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   beginwork.WhenworkTable,
			Columns: []string{beginwork.WhenworkColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: employeeworkinghours.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bwu.mutation.WhenworkIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   beginwork.WhenworkTable,
			Columns: []string{beginwork.WhenworkColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: employeeworkinghours.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bwu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{beginwork.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// BeginWorkUpdateOne is the builder for updating a single BeginWork entity.
type BeginWorkUpdateOne struct {
	config
	hooks    []Hook
	mutation *BeginWorkMutation
}

// SetBeginWork sets the BeginWork field.
func (bwuo *BeginWorkUpdateOne) SetBeginWork(t time.Time) *BeginWorkUpdateOne {
	bwuo.mutation.SetBeginWork(t)
	return bwuo
}

// AddWhenworkIDs adds the whenwork edge to EmployeeWorkingHours by ids.
func (bwuo *BeginWorkUpdateOne) AddWhenworkIDs(ids ...int) *BeginWorkUpdateOne {
	bwuo.mutation.AddWhenworkIDs(ids...)
	return bwuo
}

// AddWhenwork adds the whenwork edges to EmployeeWorkingHours.
func (bwuo *BeginWorkUpdateOne) AddWhenwork(e ...*EmployeeWorkingHours) *BeginWorkUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return bwuo.AddWhenworkIDs(ids...)
}

// Mutation returns the BeginWorkMutation object of the builder.
func (bwuo *BeginWorkUpdateOne) Mutation() *BeginWorkMutation {
	return bwuo.mutation
}

// RemoveWhenworkIDs removes the whenwork edge to EmployeeWorkingHours by ids.
func (bwuo *BeginWorkUpdateOne) RemoveWhenworkIDs(ids ...int) *BeginWorkUpdateOne {
	bwuo.mutation.RemoveWhenworkIDs(ids...)
	return bwuo
}

// RemoveWhenwork removes whenwork edges to EmployeeWorkingHours.
func (bwuo *BeginWorkUpdateOne) RemoveWhenwork(e ...*EmployeeWorkingHours) *BeginWorkUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return bwuo.RemoveWhenworkIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (bwuo *BeginWorkUpdateOne) Save(ctx context.Context) (*BeginWork, error) {

	var (
		err  error
		node *BeginWork
	)
	if len(bwuo.hooks) == 0 {
		node, err = bwuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BeginWorkMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bwuo.mutation = mutation
			node, err = bwuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(bwuo.hooks) - 1; i >= 0; i-- {
			mut = bwuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bwuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (bwuo *BeginWorkUpdateOne) SaveX(ctx context.Context) *BeginWork {
	bw, err := bwuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return bw
}

// Exec executes the query on the entity.
func (bwuo *BeginWorkUpdateOne) Exec(ctx context.Context) error {
	_, err := bwuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bwuo *BeginWorkUpdateOne) ExecX(ctx context.Context) {
	if err := bwuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (bwuo *BeginWorkUpdateOne) sqlSave(ctx context.Context) (bw *BeginWork, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   beginwork.Table,
			Columns: beginwork.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: beginwork.FieldID,
			},
		},
	}
	id, ok := bwuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing BeginWork.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := bwuo.mutation.BeginWork(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: beginwork.FieldBeginWork,
		})
	}
	if nodes := bwuo.mutation.RemovedWhenworkIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   beginwork.WhenworkTable,
			Columns: []string{beginwork.WhenworkColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: employeeworkinghours.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bwuo.mutation.WhenworkIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   beginwork.WhenworkTable,
			Columns: []string{beginwork.WhenworkColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: employeeworkinghours.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	bw = &BeginWork{config: bwuo.config}
	_spec.Assign = bw.assignValues
	_spec.ScanValues = bw.scanValues()
	if err = sqlgraph.UpdateNode(ctx, bwuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{beginwork.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return bw, nil
}
