// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/tanapon395/playlist-video/ent/day"
	"github.com/tanapon395/playlist-video/ent/employeeworkinghours"
)

// DayCreate is the builder for creating a Day entity.
type DayCreate struct {
	config
	mutation *DayMutation
	hooks    []Hook
}

// SetDay sets the Day field.
func (dc *DayCreate) SetDay(s string) *DayCreate {
	dc.mutation.SetDay(s)
	return dc
}

// AddWhatdayIDs adds the whatday edge to Employeeworkinghours by ids.
func (dc *DayCreate) AddWhatdayIDs(ids ...int) *DayCreate {
	dc.mutation.AddWhatdayIDs(ids...)
	return dc
}

// AddWhatday adds the whatday edges to Employeeworkinghours.
func (dc *DayCreate) AddWhatday(e ...*Employeeworkinghours) *DayCreate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return dc.AddWhatdayIDs(ids...)
}

// Mutation returns the DayMutation object of the builder.
func (dc *DayCreate) Mutation() *DayMutation {
	return dc.mutation
}

// Save creates the Day in the database.
func (dc *DayCreate) Save(ctx context.Context) (*Day, error) {
	if _, ok := dc.mutation.Day(); !ok {
		return nil, &ValidationError{Name: "Day", err: errors.New("ent: missing required field \"Day\"")}
	}
	var (
		err  error
		node *Day
	)
	if len(dc.hooks) == 0 {
		node, err = dc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DayMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			dc.mutation = mutation
			node, err = dc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(dc.hooks) - 1; i >= 0; i-- {
			mut = dc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (dc *DayCreate) SaveX(ctx context.Context) *Day {
	v, err := dc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (dc *DayCreate) sqlSave(ctx context.Context) (*Day, error) {
	d, _spec := dc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	d.ID = int(id)
	return d, nil
}

func (dc *DayCreate) createSpec() (*Day, *sqlgraph.CreateSpec) {
	var (
		d     = &Day{config: dc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: day.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: day.FieldID,
			},
		}
	)
	if value, ok := dc.mutation.Day(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: day.FieldDay,
		})
		d.Day = value
	}
	if nodes := dc.mutation.WhatdayIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   day.WhatdayTable,
			Columns: []string{day.WhatdayColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: employeeworkinghours.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return d, _spec
}
