// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/tanapon395/playlist-video/ent/orderonline"
	"github.com/tanapon395/playlist-video/ent/orderproduct"
	"github.com/tanapon395/playlist-video/ent/predicate"
	"github.com/tanapon395/playlist-video/ent/stock"
	"github.com/tanapon395/playlist-video/ent/typeproduct"
)

// TypeproductUpdate is the builder for updating Typeproduct entities.
type TypeproductUpdate struct {
	config
	hooks      []Hook
	mutation   *TypeproductMutation
	predicates []predicate.Typeproduct
}

// Where adds a new predicate for the builder.
func (tu *TypeproductUpdate) Where(ps ...predicate.Typeproduct) *TypeproductUpdate {
	tu.predicates = append(tu.predicates, ps...)
	return tu
}

// SetTypeproduct sets the Typeproduct field.
func (tu *TypeproductUpdate) SetTypeproduct(s string) *TypeproductUpdate {
	tu.mutation.SetTypeproduct(s)
	return tu
}

// AddTypestockIDs adds the typestock edge to Stock by ids.
func (tu *TypeproductUpdate) AddTypestockIDs(ids ...int) *TypeproductUpdate {
	tu.mutation.AddTypestockIDs(ids...)
	return tu
}

// AddTypestock adds the typestock edges to Stock.
func (tu *TypeproductUpdate) AddTypestock(s ...*Stock) *TypeproductUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return tu.AddTypestockIDs(ids...)
}

// AddTypeproductIDs adds the Typeproducts edge to Orderproduct by ids.
func (tu *TypeproductUpdate) AddTypeproductIDs(ids ...int) *TypeproductUpdate {
	tu.mutation.AddTypeproductIDs(ids...)
	return tu
}

// AddTypeproducts adds the Typeproducts edges to Orderproduct.
func (tu *TypeproductUpdate) AddTypeproducts(o ...*Orderproduct) *TypeproductUpdate {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return tu.AddTypeproductIDs(ids...)
}

// AddFromTypeproductonlineIDs adds the fromTypeproductonline edge to Orderonline by ids.
func (tu *TypeproductUpdate) AddFromTypeproductonlineIDs(ids ...int) *TypeproductUpdate {
	tu.mutation.AddFromTypeproductonlineIDs(ids...)
	return tu
}

// AddFromTypeproductonline adds the fromTypeproductonline edges to Orderonline.
func (tu *TypeproductUpdate) AddFromTypeproductonline(o ...*Orderonline) *TypeproductUpdate {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return tu.AddFromTypeproductonlineIDs(ids...)
}

// Mutation returns the TypeproductMutation object of the builder.
func (tu *TypeproductUpdate) Mutation() *TypeproductMutation {
	return tu.mutation
}

// RemoveTypestockIDs removes the typestock edge to Stock by ids.
func (tu *TypeproductUpdate) RemoveTypestockIDs(ids ...int) *TypeproductUpdate {
	tu.mutation.RemoveTypestockIDs(ids...)
	return tu
}

// RemoveTypestock removes typestock edges to Stock.
func (tu *TypeproductUpdate) RemoveTypestock(s ...*Stock) *TypeproductUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return tu.RemoveTypestockIDs(ids...)
}

// RemoveTypeproductIDs removes the Typeproducts edge to Orderproduct by ids.
func (tu *TypeproductUpdate) RemoveTypeproductIDs(ids ...int) *TypeproductUpdate {
	tu.mutation.RemoveTypeproductIDs(ids...)
	return tu
}

// RemoveTypeproducts removes Typeproducts edges to Orderproduct.
func (tu *TypeproductUpdate) RemoveTypeproducts(o ...*Orderproduct) *TypeproductUpdate {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return tu.RemoveTypeproductIDs(ids...)
}

// RemoveFromTypeproductonlineIDs removes the fromTypeproductonline edge to Orderonline by ids.
func (tu *TypeproductUpdate) RemoveFromTypeproductonlineIDs(ids ...int) *TypeproductUpdate {
	tu.mutation.RemoveFromTypeproductonlineIDs(ids...)
	return tu
}

// RemoveFromTypeproductonline removes fromTypeproductonline edges to Orderonline.
func (tu *TypeproductUpdate) RemoveFromTypeproductonline(o ...*Orderonline) *TypeproductUpdate {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return tu.RemoveFromTypeproductonlineIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (tu *TypeproductUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := tu.mutation.Typeproduct(); ok {
		if err := typeproduct.TypeproductValidator(v); err != nil {
			return 0, &ValidationError{Name: "Typeproduct", err: fmt.Errorf("ent: validator failed for field \"Typeproduct\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(tu.hooks) == 0 {
		affected, err = tu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TypeproductMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tu.mutation = mutation
			affected, err = tu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tu.hooks) - 1; i >= 0; i-- {
			mut = tu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TypeproductUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TypeproductUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TypeproductUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tu *TypeproductUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   typeproduct.Table,
			Columns: typeproduct.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: typeproduct.FieldID,
			},
		},
	}
	if ps := tu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.Typeproduct(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: typeproduct.FieldTypeproduct,
		})
	}
	if nodes := tu.mutation.RemovedTypestockIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   typeproduct.TypestockTable,
			Columns: []string{typeproduct.TypestockColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: stock.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.TypestockIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   typeproduct.TypestockTable,
			Columns: []string{typeproduct.TypestockColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: stock.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := tu.mutation.RemovedTypeproductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   typeproduct.TypeproductsTable,
			Columns: []string{typeproduct.TypeproductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: orderproduct.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.TypeproductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   typeproduct.TypeproductsTable,
			Columns: []string{typeproduct.TypeproductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: orderproduct.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := tu.mutation.RemovedFromTypeproductonlineIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   typeproduct.FromTypeproductonlineTable,
			Columns: []string{typeproduct.FromTypeproductonlineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: orderonline.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.FromTypeproductonlineIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   typeproduct.FromTypeproductonlineTable,
			Columns: []string{typeproduct.FromTypeproductonlineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: orderonline.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{typeproduct.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// TypeproductUpdateOne is the builder for updating a single Typeproduct entity.
type TypeproductUpdateOne struct {
	config
	hooks    []Hook
	mutation *TypeproductMutation
}

// SetTypeproduct sets the Typeproduct field.
func (tuo *TypeproductUpdateOne) SetTypeproduct(s string) *TypeproductUpdateOne {
	tuo.mutation.SetTypeproduct(s)
	return tuo
}

// AddTypestockIDs adds the typestock edge to Stock by ids.
func (tuo *TypeproductUpdateOne) AddTypestockIDs(ids ...int) *TypeproductUpdateOne {
	tuo.mutation.AddTypestockIDs(ids...)
	return tuo
}

// AddTypestock adds the typestock edges to Stock.
func (tuo *TypeproductUpdateOne) AddTypestock(s ...*Stock) *TypeproductUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return tuo.AddTypestockIDs(ids...)
}

// AddTypeproductIDs adds the Typeproducts edge to Orderproduct by ids.
func (tuo *TypeproductUpdateOne) AddTypeproductIDs(ids ...int) *TypeproductUpdateOne {
	tuo.mutation.AddTypeproductIDs(ids...)
	return tuo
}

// AddTypeproducts adds the Typeproducts edges to Orderproduct.
func (tuo *TypeproductUpdateOne) AddTypeproducts(o ...*Orderproduct) *TypeproductUpdateOne {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return tuo.AddTypeproductIDs(ids...)
}

// AddFromTypeproductonlineIDs adds the fromTypeproductonline edge to Orderonline by ids.
func (tuo *TypeproductUpdateOne) AddFromTypeproductonlineIDs(ids ...int) *TypeproductUpdateOne {
	tuo.mutation.AddFromTypeproductonlineIDs(ids...)
	return tuo
}

// AddFromTypeproductonline adds the fromTypeproductonline edges to Orderonline.
func (tuo *TypeproductUpdateOne) AddFromTypeproductonline(o ...*Orderonline) *TypeproductUpdateOne {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return tuo.AddFromTypeproductonlineIDs(ids...)
}

// Mutation returns the TypeproductMutation object of the builder.
func (tuo *TypeproductUpdateOne) Mutation() *TypeproductMutation {
	return tuo.mutation
}

// RemoveTypestockIDs removes the typestock edge to Stock by ids.
func (tuo *TypeproductUpdateOne) RemoveTypestockIDs(ids ...int) *TypeproductUpdateOne {
	tuo.mutation.RemoveTypestockIDs(ids...)
	return tuo
}

// RemoveTypestock removes typestock edges to Stock.
func (tuo *TypeproductUpdateOne) RemoveTypestock(s ...*Stock) *TypeproductUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return tuo.RemoveTypestockIDs(ids...)
}

// RemoveTypeproductIDs removes the Typeproducts edge to Orderproduct by ids.
func (tuo *TypeproductUpdateOne) RemoveTypeproductIDs(ids ...int) *TypeproductUpdateOne {
	tuo.mutation.RemoveTypeproductIDs(ids...)
	return tuo
}

// RemoveTypeproducts removes Typeproducts edges to Orderproduct.
func (tuo *TypeproductUpdateOne) RemoveTypeproducts(o ...*Orderproduct) *TypeproductUpdateOne {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return tuo.RemoveTypeproductIDs(ids...)
}

// RemoveFromTypeproductonlineIDs removes the fromTypeproductonline edge to Orderonline by ids.
func (tuo *TypeproductUpdateOne) RemoveFromTypeproductonlineIDs(ids ...int) *TypeproductUpdateOne {
	tuo.mutation.RemoveFromTypeproductonlineIDs(ids...)
	return tuo
}

// RemoveFromTypeproductonline removes fromTypeproductonline edges to Orderonline.
func (tuo *TypeproductUpdateOne) RemoveFromTypeproductonline(o ...*Orderonline) *TypeproductUpdateOne {
	ids := make([]int, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return tuo.RemoveFromTypeproductonlineIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (tuo *TypeproductUpdateOne) Save(ctx context.Context) (*Typeproduct, error) {
	if v, ok := tuo.mutation.Typeproduct(); ok {
		if err := typeproduct.TypeproductValidator(v); err != nil {
			return nil, &ValidationError{Name: "Typeproduct", err: fmt.Errorf("ent: validator failed for field \"Typeproduct\": %w", err)}
		}
	}

	var (
		err  error
		node *Typeproduct
	)
	if len(tuo.hooks) == 0 {
		node, err = tuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TypeproductMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tuo.mutation = mutation
			node, err = tuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(tuo.hooks) - 1; i >= 0; i-- {
			mut = tuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TypeproductUpdateOne) SaveX(ctx context.Context) *Typeproduct {
	t, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return t
}

// Exec executes the query on the entity.
func (tuo *TypeproductUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TypeproductUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tuo *TypeproductUpdateOne) sqlSave(ctx context.Context) (t *Typeproduct, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   typeproduct.Table,
			Columns: typeproduct.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: typeproduct.FieldID,
			},
		},
	}
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Typeproduct.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := tuo.mutation.Typeproduct(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: typeproduct.FieldTypeproduct,
		})
	}
	if nodes := tuo.mutation.RemovedTypestockIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   typeproduct.TypestockTable,
			Columns: []string{typeproduct.TypestockColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: stock.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.TypestockIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   typeproduct.TypestockTable,
			Columns: []string{typeproduct.TypestockColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: stock.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := tuo.mutation.RemovedTypeproductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   typeproduct.TypeproductsTable,
			Columns: []string{typeproduct.TypeproductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: orderproduct.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.TypeproductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   typeproduct.TypeproductsTable,
			Columns: []string{typeproduct.TypeproductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: orderproduct.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := tuo.mutation.RemovedFromTypeproductonlineIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   typeproduct.FromTypeproductonlineTable,
			Columns: []string{typeproduct.FromTypeproductonlineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: orderonline.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.FromTypeproductonlineIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   typeproduct.FromTypeproductonlineTable,
			Columns: []string{typeproduct.FromTypeproductonlineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: orderonline.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	t = &Typeproduct{config: tuo.config}
	_spec.Assign = t.assignValues
	_spec.ScanValues = t.scanValues()
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{typeproduct.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return t, nil
}
