// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/tanapon395/playlist-video/ent/predicate"
	"github.com/tanapon395/playlist-video/ent/zoneproduct"
)

// ZoneproductDelete is the builder for deleting a Zoneproduct entity.
type ZoneproductDelete struct {
	config
	hooks      []Hook
	mutation   *ZoneproductMutation
	predicates []predicate.Zoneproduct
}

// Where adds a new predicate to the delete builder.
func (zd *ZoneproductDelete) Where(ps ...predicate.Zoneproduct) *ZoneproductDelete {
	zd.predicates = append(zd.predicates, ps...)
	return zd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (zd *ZoneproductDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(zd.hooks) == 0 {
		affected, err = zd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ZoneproductMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			zd.mutation = mutation
			affected, err = zd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(zd.hooks) - 1; i >= 0; i-- {
			mut = zd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, zd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (zd *ZoneproductDelete) ExecX(ctx context.Context) int {
	n, err := zd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (zd *ZoneproductDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: zoneproduct.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: zoneproduct.FieldID,
			},
		},
	}
	if ps := zd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, zd.driver, _spec)
}

// ZoneproductDeleteOne is the builder for deleting a single Zoneproduct entity.
type ZoneproductDeleteOne struct {
	zd *ZoneproductDelete
}

// Exec executes the deletion query.
func (zdo *ZoneproductDeleteOne) Exec(ctx context.Context) error {
	n, err := zdo.zd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{zoneproduct.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (zdo *ZoneproductDeleteOne) ExecX(ctx context.Context) {
	zdo.zd.ExecX(ctx)
}
