// Code generated by entc, DO NOT EDIT.

package endwork

import (
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/team13/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.EndWork {
	return predicate.EndWork(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.EndWork {
	return predicate.EndWork(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.EndWork {
	return predicate.EndWork(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.EndWork {
	return predicate.EndWork(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.EndWork {
	return predicate.EndWork(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.EndWork {
	return predicate.EndWork(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.EndWork {
	return predicate.EndWork(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.EndWork {
	return predicate.EndWork(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.EndWork {
	return predicate.EndWork(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// EndWork applies equality check predicate on the "EndWork" field. It's identical to EndWorkEQ.
func EndWork(v time.Time) predicate.EndWork {
	return predicate.EndWork(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldEndWork), v))
	})
}

// EndWorkEQ applies the EQ predicate on the "EndWork" field.
func EndWorkEQ(v time.Time) predicate.EndWork {
	return predicate.EndWork(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldEndWork), v))
	})
}

// EndWorkNEQ applies the NEQ predicate on the "EndWork" field.
func EndWorkNEQ(v time.Time) predicate.EndWork {
	return predicate.EndWork(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldEndWork), v))
	})
}

// EndWorkIn applies the In predicate on the "EndWork" field.
func EndWorkIn(vs ...time.Time) predicate.EndWork {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EndWork(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldEndWork), v...))
	})
}

// EndWorkNotIn applies the NotIn predicate on the "EndWork" field.
func EndWorkNotIn(vs ...time.Time) predicate.EndWork {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EndWork(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldEndWork), v...))
	})
}

// EndWorkGT applies the GT predicate on the "EndWork" field.
func EndWorkGT(v time.Time) predicate.EndWork {
	return predicate.EndWork(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldEndWork), v))
	})
}

// EndWorkGTE applies the GTE predicate on the "EndWork" field.
func EndWorkGTE(v time.Time) predicate.EndWork {
	return predicate.EndWork(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldEndWork), v))
	})
}

// EndWorkLT applies the LT predicate on the "EndWork" field.
func EndWorkLT(v time.Time) predicate.EndWork {
	return predicate.EndWork(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldEndWork), v))
	})
}

// EndWorkLTE applies the LTE predicate on the "EndWork" field.
func EndWorkLTE(v time.Time) predicate.EndWork {
	return predicate.EndWork(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldEndWork), v))
	})
}

// HasWhenendwork applies the HasEdge predicate on the "whenendwork" edge.
func HasWhenendwork() predicate.EndWork {
	return predicate.EndWork(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(WhenendworkTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, WhenendworkTable, WhenendworkColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWhenendworkWith applies the HasEdge predicate on the "whenendwork" edge with a given conditions (other predicates).
func HasWhenendworkWith(preds ...predicate.EmployeeWorkingHours) predicate.EndWork {
	return predicate.EndWork(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(WhenendworkInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, WhenendworkTable, WhenendworkColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.EndWork) predicate.EndWork {
	return predicate.EndWork(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.EndWork) predicate.EndWork {
	return predicate.EndWork(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EndWork) predicate.EndWork {
	return predicate.EndWork(func(s *sql.Selector) {
		p(s.Not())
	})
}
