/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersPromotion
 */
export interface ControllersPromotion {
    /**
     * 
     * @type {number}
     * @memberof ControllersPromotion
     */
    discount?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersPromotion
     */
    giveaway?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersPromotion
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersPromotion
     */
    product?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersPromotion
     */
    promotionName?: string;
}

export function ControllersPromotionFromJSON(json: any): ControllersPromotion {
    return ControllersPromotionFromJSONTyped(json, false);
}

export function ControllersPromotionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersPromotion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'discount': !exists(json, 'discount') ? undefined : json['discount'],
        'giveaway': !exists(json, 'giveaway') ? undefined : json['giveaway'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'product': !exists(json, 'product') ? undefined : json['product'],
        'promotionName': !exists(json, 'promotionName') ? undefined : json['promotionName'],
    };
}

export function ControllersPromotionToJSON(value?: ControllersPromotion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Discount': value.discount,
        'Giveaway': value.giveaway,
        'Price': value.price,
        'Product': value.product,
        'PromotionName': value.promotionName,
    };
}


