/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntSalary,
    EntSalaryFromJSON,
    EntSalaryFromJSONTyped,
    EntSalaryToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntAssessmentEdges
 */
export interface EntAssessmentEdges {
    /**
     * Formassessment holds the value of the formassessment edge.
     * @type {Array<EntSalary>}
     * @memberof EntAssessmentEdges
     */
    formassessment?: Array<EntSalary>;
}

export function EntAssessmentEdgesFromJSON(json: any): EntAssessmentEdges {
    return EntAssessmentEdgesFromJSONTyped(json, false);
}

export function EntAssessmentEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntAssessmentEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'formassessment': !exists(json, 'formassessment') ? undefined : ((json['formassessment'] as Array<any>).map(EntSalaryFromJSON)),
    };
}

export function EntAssessmentEdgesToJSON(value?: EntAssessmentEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'formassessment': value.formassessment === undefined ? undefined : ((value.formassessment as Array<any>).map(EntSalaryToJSON)),
    };
}


