/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntEmployeeWorkingHours,
    EntEmployeeWorkingHoursFromJSON,
    EntEmployeeWorkingHoursFromJSONTyped,
    EntEmployeeWorkingHoursToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntDayEdges
 */
export interface EntDayEdges {
    /**
     * Whatday holds the value of the whatday edge.
     * @type {Array<EntEmployeeWorkingHours>}
     * @memberof EntDayEdges
     */
    whatday?: Array<EntEmployeeWorkingHours>;
}

export function EntDayEdgesFromJSON(json: any): EntDayEdges {
    return EntDayEdgesFromJSONTyped(json, false);
}

export function EntDayEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntDayEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'whatday': !exists(json, 'whatday') ? undefined : ((json['whatday'] as Array<any>).map(EntEmployeeWorkingHoursFromJSON)),
    };
}

export function EntDayEdgesToJSON(value?: EntDayEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'whatday': value.whatday === undefined ? undefined : ((value.whatday as Array<any>).map(EntEmployeeWorkingHoursToJSON)),
    };
}


