/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntOrderproductEdges,
    EntOrderproductEdgesFromJSON,
    EntOrderproductEdgesFromJSONTyped,
    EntOrderproductEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntOrderproduct
 */
export interface EntOrderproduct {
    /**
     * Addedtime holds the value of the "addedtime" field.
     * @type {string}
     * @memberof EntOrderproduct
     */
    addedtime?: string;
    /**
     * 
     * @type {EntOrderproductEdges}
     * @memberof EntOrderproduct
     */
    edges?: EntOrderproductEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntOrderproduct
     */
    id?: number;
    /**
     * Stock holds the value of the "stock" field.
     * @type {number}
     * @memberof EntOrderproduct
     */
    stock?: number;
}

export function EntOrderproductFromJSON(json: any): EntOrderproduct {
    return EntOrderproductFromJSONTyped(json, false);
}

export function EntOrderproductFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntOrderproduct {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addedtime': !exists(json, 'addedtime') ? undefined : json['addedtime'],
        'edges': !exists(json, 'edges') ? undefined : EntOrderproductEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'stock': !exists(json, 'stock') ? undefined : json['stock'],
    };
}

export function EntOrderproductToJSON(value?: EntOrderproduct | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'addedtime': value.addedtime,
        'edges': EntOrderproductEdgesToJSON(value.edges),
        'id': value.id,
        'stock': value.stock,
    };
}


