/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntOrderonline,
    EntOrderonlineFromJSON,
    EntOrderonlineFromJSONTyped,
    EntOrderonlineToJSON,
    EntOrderproduct,
    EntOrderproductFromJSON,
    EntOrderproductFromJSONTyped,
    EntOrderproductToJSON,
    EntPromotion,
    EntPromotionFromJSON,
    EntPromotionFromJSONTyped,
    EntPromotionToJSON,
    EntStock,
    EntStockFromJSON,
    EntStockFromJSONTyped,
    EntStockToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntProductEdges
 */
export interface EntProductEdges {
    /**
     * Formproductonline holds the value of the formproductonline edge.
     * @type {Array<EntOrderonline>}
     * @memberof EntProductEdges
     */
    formproductonline?: Array<EntOrderonline>;
    /**
     * Forproduct holds the value of the forproduct edge.
     * @type {Array<EntPromotion>}
     * @memberof EntProductEdges
     */
    forproduct?: Array<EntPromotion>;
    /**
     * Products holds the value of the products edge.
     * @type {Array<EntOrderproduct>}
     * @memberof EntProductEdges
     */
    products?: Array<EntOrderproduct>;
    /**
     * Stockproduct holds the value of the stockproduct edge.
     * @type {Array<EntStock>}
     * @memberof EntProductEdges
     */
    stockproduct?: Array<EntStock>;
}

export function EntProductEdgesFromJSON(json: any): EntProductEdges {
    return EntProductEdgesFromJSONTyped(json, false);
}

export function EntProductEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntProductEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'formproductonline': !exists(json, 'formproductonline') ? undefined : ((json['formproductonline'] as Array<any>).map(EntOrderonlineFromJSON)),
        'forproduct': !exists(json, 'forproduct') ? undefined : ((json['forproduct'] as Array<any>).map(EntPromotionFromJSON)),
        'products': !exists(json, 'products') ? undefined : ((json['products'] as Array<any>).map(EntOrderproductFromJSON)),
        'stockproduct': !exists(json, 'stockproduct') ? undefined : ((json['stockproduct'] as Array<any>).map(EntStockFromJSON)),
    };
}

export function EntProductEdgesToJSON(value?: EntProductEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'formproductonline': value.formproductonline === undefined ? undefined : ((value.formproductonline as Array<any>).map(EntOrderonlineToJSON)),
        'forproduct': value.forproduct === undefined ? undefined : ((value.forproduct as Array<any>).map(EntPromotionToJSON)),
        'products': value.products === undefined ? undefined : ((value.products as Array<any>).map(EntOrderproductToJSON)),
        'stockproduct': value.stockproduct === undefined ? undefined : ((value.stockproduct as Array<any>).map(EntStockToJSON)),
    };
}


