/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntEmployeeWorkingHours,
    EntEmployeeWorkingHoursFromJSON,
    EntEmployeeWorkingHoursFromJSONTyped,
    EntEmployeeWorkingHoursToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntRoleEdges
 */
export interface EntRoleEdges {
    /**
     * Todo holds the value of the todo edge.
     * @type {Array<EntEmployeeWorkingHours>}
     * @memberof EntRoleEdges
     */
    todo?: Array<EntEmployeeWorkingHours>;
}

export function EntRoleEdgesFromJSON(json: any): EntRoleEdges {
    return EntRoleEdgesFromJSONTyped(json, false);
}

export function EntRoleEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntRoleEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'todo': !exists(json, 'todo') ? undefined : ((json['todo'] as Array<any>).map(EntEmployeeWorkingHoursFromJSON)),
    };
}

export function EntRoleEdgesToJSON(value?: EntRoleEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'todo': value.todo === undefined ? undefined : ((value.todo as Array<any>).map(EntEmployeeWorkingHoursToJSON)),
    };
}


