/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntShiftEdges,
    EntShiftEdgesFromJSON,
    EntShiftEdgesFromJSONTyped,
    EntShiftEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntShift
 */
export interface EntShift {
    /**
     * TimeEnd holds the value of the "TimeEnd" field.
     * @type {string}
     * @memberof EntShift
     */
    timeEnd?: string;
    /**
     * TimeStart holds the value of the "TimeStart" field.
     * @type {string}
     * @memberof EntShift
     */
    timeStart?: string;
    /**
     * 
     * @type {EntShiftEdges}
     * @memberof EntShift
     */
    edges?: EntShiftEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntShift
     */
    id?: number;
}

export function EntShiftFromJSON(json: any): EntShift {
    return EntShiftFromJSONTyped(json, false);
}

export function EntShiftFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntShift {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'timeEnd': !exists(json, 'TimeEnd') ? undefined : json['TimeEnd'],
        'timeStart': !exists(json, 'TimeStart') ? undefined : json['TimeStart'],
        'edges': !exists(json, 'edges') ? undefined : EntShiftEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntShiftToJSON(value?: EntShift | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'TimeEnd': value.timeEnd,
        'TimeStart': value.timeStart,
        'edges': EntShiftEdgesToJSON(value.edges),
        'id': value.id,
    };
}


